// Maine Lodge 1958 — Classic Cribbage Table Banter Tone Pack
// Warm but competitive, dry humor, old-school card slang
// "Cribbage in a Maine lodge in 1958."

export const MAINE_LODGE_PHRASES = {
  bigHands: [
    "Now there's a hand.",
    "You don't see that every day.",
    "Well I'll be.",
    "Somebody fed those cards.",
    "That's a keeper.",
    "Not too shabby.",
    "Now you're talkin'.",
    "That hand's got legs.",
    "You could hang that one on the wall.",
    "Cards were runnin' your way.",
    "That's a hand and a half.",
    "The good Lord was dealin' for ya.",
    "Better than a poke in the eye.",
    "That'll move the pegs a ways.",
    "You drew the long straw on that one.",
    "Some hands you just tip your hat to.",
    "That's the one you wait for.",
    "There's your hand right there.",
    "Now that's proper cribbage.",
    "You could ride that hand all the way home.",
    "That hand just put its boots on.",
    "Cards like that don't grow on trees.",
    "Well, well, well.",
    "That's what you keep the score pegs sharp for.",
    "The cut card was feelin' generous.",
    "You won't complain about that one.",
    "That's a fireside hand.",
    "Somebody dealt you a winner.",
    "That hand's got character.",
    "The cards were cookin' tonight.",
  ],

  pegging: [
    "Sharp peggin'.",
    "You got 'em with that one.",
    "Slick play.",
    "That peg had eyes.",
    "Knew you were sittin' on that.",
    "Good card to hold back.",
    "That's how the old-timers do it.",
    "You saw that comin' a mile off.",
    "Steady hand on the pegs tonight.",
    "Clean play. Real clean.",
    "You're peggin' like you wrote the rules.",
    "That card was waitin' in the weeds.",
    "Nice bit of peggin'.",
    "Thirty-one on the money.",
    "You counted that out perfect.",
    "Good feel for the count.",
    "That play had some thought behind it.",
    "Peggin' with purpose.",
    "You don't give up easy, do ya.",
    "Smart. Real smart.",
    "That peg just earned its keep.",
    "Right on the number.",
    "Patient play. I like it.",
    "You played that close to the vest.",
    "That card did exactly what you needed.",
  ],

  zeroHands: [
    "Wellp.",
    "The cards'll come around.",
    "Can't win 'em all.",
    "Thin hand.",
    "Could use a little help from the crib.",
    "Been there.",
    "Sometimes that's how she goes.",
    "Nothin' doin'.",
    "The cards owe you one.",
    "Cold hand.",
    "That's a shaker. Shake it off.",
    "Dry well.",
    "Even the cut couldn't save that one.",
    "Tough deal.",
    "You'll get 'em next hand.",
    "Can't dress up a hand like that.",
    "Light on points.",
    "The deck wasn't feelin' charitable.",
    "That hand needed a miracle.",
    "Next hand's a new deal.",
  ],

  gameEvents: [
    "Good game. Shake on it.",
    "Down to the wire.",
    "Tight one.",
    "That one could've gone either way.",
    "Squeaker.",
    "Close as a barn door in January.",
    "That was a proper game.",
    "Right down to the last peg.",
    "You earned that one.",
    "Game well played.",
    "She was tight the whole way.",
    "Close enough to make ya sweat.",
    "That's a game you remember.",
    "Another deal, another story.",
    "The board was full of drama tonight.",
    "Skunked. Don't let it eat at ya.",
    "A skunkin'. We'll keep that between us.",
    "That was a thumpin'. Tip of the cap.",
    "You ran away with that one.",
    "Couldn't catch ya.",
    "Never in doubt. For you, anyway.",
    "You came from behind on that one.",
    "Gutsy finish.",
    "That comeback had whiskers on it.",
    "The old dog still hunts.",
  ],

  crib: [
    "The crib was loaded.",
    "That crib's heavier than a cast iron skillet.",
    "The crib came through.",
    "Good things in the crib tonight.",
    "The crib paid the bills.",
    "Somebody put the good cards in the crib.",
    "That crib had a mind of its own.",
    "Crib's got more points than the hand.",
    "The crib earned its keep.",
    "You can't complain about a crib like that.",
    "That crib's sittin' pretty.",
    "Crib came in hot.",
    "A crib worth waitin' for.",
    "The crib did the heavy liftin'.",
    "Better in the crib than against it.",
  ],

  cutCard: [
    "The cut card was kind.",
    "That cut changed everything.",
    "Nice cut.",
    "The deck had one more trick.",
    "The right card at the right time.",
    "That cut just made the hand.",
    "Cut yourself a winner there.",
    "The cut was sittin' on top waitin' for ya.",
    "Couldn't have cut it better yourself.",
    "That cut's got your name on it.",
  ],

  hisHeels: [
    "His heels. Two for the house.",
    "Jack on the cut. Dealer's reward.",
    "His heels \u2014 don't spend 'em all in one place.",
    "There's your Jack.",
    "His heels. A little somethin' for the kitty.",
    "Jack right on top. Figured.",
    "His heels \u2014 the deck's tip of the hat to the dealer.",
    "Cut a Jack. There you go.",
    "His heels. Like clockwork.",
    "Two for his heels. A fine start.",
  ],

  rare: [
    "That hand's got more points than a porcupine.",
    "You're peggin' like you've got a ouija board under the table.",
    "That hand just walked in, sat down, and ordered a double.",
    "Skunked. Smells like it too.",
    "If that hand were any bigger, it'd need its own zip code.",
  ],
};
